MAGETWO-48382: Conflict resolution doesn't work for Paypal Express Checkout
- Fixed "Uncaught TypeError: this.rules[this.name] is not a function" js error
- Fixed confirm predicate error