Added module dependecy
Removing the module inventory-source-selection and trying to create an invoice in the backend, the following error message is displayed: 
Fatal error: Uncaught Error: Cannot instantiate interface Magento\InventorySourceSelectionApi\Api\GetDefaultSourceSelectionAlgorithmCodeInterface in /var/www/silber-studio-m2/vendor/magento/framework/ObjectManager/Factory/AbstractFactory.php:116 Stack trace: #0 /var/www/silber-studio-m2/vendor/magento/framework/ObjectManager/Factory/Compiled.php(108): Magento\Framework\ObjectManager\Factory\AbstractFactory->createObject('Magento\\Invento...', Array) #1 /var/www/silber-studio-m2/vendor/magento/framework/ObjectManager/Factory/Compiled.php(150): Magento\Framework\ObjectManager\Factory\Compiled->create('Magento\\Invento...') #2 /var/www/silber-studio-m2/vendor/magento/framework/ObjectManager/Factory/Compiled.php(79): Magento\Framework\ObjectManager\Factory\Compiled->get('Magento\\Invento...') #3 /var/www/silber-studio-m2/vendor/magento/framework/ObjectManager/Factory/Compiled.php(150): Magento\Framework\ObjectManager\Factory\Compiled->create('Magento\\Invento...') #4 /var/www/silber-studio-m2/vendor/magento/framework/ObjectMa in /var/www/silber-studio-m2/vendor/magento/framework/ObjectManager/Factory/AbstractFactory.php on line 116

This can be solved by activating the mentioned module, so this dependency should be added.