fix: customer account create page does not work
Fixes this exception which made the create account page unusable:

```
Exception: Deprecated Functionality: trim(): Passing null to parameter #1 ($string) of type string is deprecated in /var/www/vendor/magento/module-customer/Block/Widget/Name.php on line 110 in /var/www/vendor/magento/framework/App/ErrorHandler.php:61
```