ADDED getThemesInUse (using [@vrann fix](https://github.com/magento/magento2/pull/8142/commits/35e3225f0478a7b952119dca2a800a76b9ae5f3e#diff-dbf04232abcedbe2e67996b043041b48) + added check for used themes in products, categories and cms pages) REF magento2/issues#10363
UnitTests are failing due to mocking problems:
```
1) Magento\Catalog\Test\Unit\Model\Product\Image\CacheTest::testGenerate
Error: Call to a member function getId() on null
``