Fixing bug in Magento/PhpStan/Formatters/FilteredErrorFormatter
This bug was causing error.

```.PHP Fatal error:  Uncaught ArgumentCountError: Too few arguments to function PHPStan\Command\AnalysisResult::__construct(), 9 passed in /var/www/html/dev/tests/static/framework/Magento/PhpStan/Formatters/FilteredErrorFormatter.php on line 70 and exactly 10 expected in phar:///var/www/html/vendor/phpstan/phpstan/phpstan.phar/src/Command/AnalysisResult.php:58
Stack trace:
```